// Structured-lesson handler: pull the lesson the student is up to from the
// curriculum, format it for WhatsApp, send it, and offer audio for the
// first audio-worthy item.

import { sendText, sendAudio } from "@/lib/messaging/whatsapp";
import { chatCompletion } from "@/lib/messaging/openai";
import { getOrCreateAudio } from "@/lib/messaging/audio-cache";
import { getAdminClient } from "@/lib/supabase/admin";
import { getMemory, patchMemory } from "@/lib/handlers/memory";
import { updateState } from "@/lib/handlers/state";
import { logMessage } from "@/lib/handlers/messages";
import { getModulesForLevel } from "@/lib/handlers/curriculum";
import type { Lesson, LessonContent, LessonItem, Plan } from "@/types";

interface LessonArgs {
  userId: string;
  whatsappNumber: string;
  teacherId: string | null;
  userMessage: string;
  // Plan-gates the audio offer at the end of the lesson. Free
  // students see phonetic spellings only; premium gets the
  // "Want to hear me say...?" prompt that triggers awaiting_audio_confirm.
  userPlan?: Plan;
}

export async function handleLesson(args: LessonArgs): Promise<void> {
  const memory = await getMemory(args.userId);
  const pos = memory.curriculum_position;

  if (!pos?.current_topic || !pos.current_lesson) {
    // No curriculum position — fall back to free chat behaviour
    await sendText(
      args.whatsappNumber,
      "Hmm — I don't have a lesson queued for you. Want to just chat for now? 🌿",
    );
    await updateState(args.userId, { state: "active_free_chat" });
    return;
  }

  const lesson = await fetchLesson({
    language: "Spanish",
    level: memory.level ?? "beginner",
    topic: pos.current_topic,
    lessonNumber: pos.current_lesson,
  });

  if (!lesson) {
    // Out of curriculum — student finished the available lessons.
    await sendText(
      args.whatsappNumber,
      "You've reached the end of what I have prepared 🌿 Let's switch to free chat — ask me anything.",
    );
    await updateState(args.userId, { state: "active_free_chat" });
    return;
  }

  // Format the lesson into a WhatsApp-friendly message via GPT (uses Chia's
  // voice). Keep it short and punchy.
  const formatted = await formatLesson(lesson, args.teacherId);
  await sendText(args.whatsappNumber, formatted);
  await logMessage({
    userId: args.userId,
    role: "assistant",
    content: formatted,
  });

  // Curriculum audio. lesson.content.audio_script is a Spanish-only
  // script pre-generated by scripts/generate-lesson-audio.mjs that
  // reads the lesson's items aloud + ends with an example sentence.
  // Available to all plans — these clips are pre-cached in Supabase
  // Storage (no per-user TTS spend, no audio quota). Best-effort: if
  // the cache lookup or send fails, the text lesson still landed.
  const audioScript = (lesson.content as { audio_script?: string }).audio_script;
  if (audioScript && audioScript.trim().length > 0) {
    try {
      const { publicUrl, fromCache } = await getOrCreateAudio(audioScript);
      if (!fromCache) {
        // Lesson audio should be pre-warmed. A cache miss here means
        // the prewarm script hasn't been run for this lesson yet —
        // log so we know to run it.
        console.warn(
          `[lesson] audio cache miss for ${lesson.level}/${lesson.topic}:${lesson.lesson_number} — run scripts/generate-lesson-audio.mjs`,
        );
      }
      await sendAudio(args.whatsappNumber, publicUrl);
    } catch (err) {
      console.error("[lesson] sendAudio failed:", err);
    }
  }

  // Enter the post-lesson interactive loop: 2-3 guided practice
  // prompts → 5-question quiz covering all the lesson's items →
  // completion. Lesson-quiz.ts owns the state machine from here.
  // Falls back to active_free_chat if startLessonPractice fails so
  // the student isn't stuck after a successful lesson delivery.
  try {
    const { startLessonPractice } = await import("@/lib/handlers/lesson-quiz");
    await startLessonPractice({
      userId: args.userId,
      whatsappNumber: args.whatsappNumber,
      lesson,
      teacherId: args.teacherId,
      userPlan: args.userPlan ?? "free",
    });
  } catch (err) {
    console.error("[lesson] startLessonPractice failed:", err);
    await updateState(args.userId, { state: "active_free_chat" });
  }
}

// Mark a specific lesson complete in user_lesson_progress. Called by
// lesson-quiz.ts when the end-of-lesson quiz finishes. Idempotent —
// re-marking a completed lesson is a no-op via upsert.
//
// This used to live inside advanceCurriculum, but was split out so
// completion happens when the student finishes the *quiz* (a real
// signal of comprehension) rather than just when they type "next
// lesson" (which doesn't prove they learned anything).
export async function markLessonComplete(
  userId: string,
  lessonId: string,
): Promise<void> {
  const sb = getAdminClient();
  await sb.from("user_lesson_progress").upsert(
    {
      user_id: userId,
      lesson_id: lessonId,
      status: "completed",
      completed_at: new Date().toISOString(),
    },
    { onConflict: "user_id,lesson_id", ignoreDuplicates: false },
  );
}

// Move curriculum_position forward to the next lesson (same topic if
// more remain, otherwise next topic in the module / next module).
// Does NOT mark the current lesson complete — that happens via
// markLessonComplete() at end-of-quiz instead. Idempotent.
export async function advanceCurriculum(userId: string): Promise<void> {
  const memory = await getMemory(userId);
  const pos = memory.curriculum_position;
  if (!pos) return;

  const sb = getAdminClient();

  // Find the next lesson, respecting MODULE ordering:
  //   1. Next lesson_number in same topic
  //   2. If topic exhausted, next topic in same module
  //   3. If module exhausted, first topic in next module
  //   4. If level exhausted, leave pointer where it is (we may
  //      advance to next level in a future commit)
  const level = memory.level ?? "beginner";
  const modules = getModulesForLevel(level);

  // Build a flat topic sequence from modules: [topic1, topic2, ...]
  // ordered by module index then topic index within module.
  const topicSequence: string[] = modules.flatMap((m) => m.topics);

  // Locate the current topic in the sequence.
  const currentTopic = pos.current_topic ?? "";
  const currentIdx = topicSequence.indexOf(currentTopic);

  // Step 1: try next lesson in same topic.
  const { data: nextInTopic } = await sb
    .from("lessons")
    .select("topic, lesson_number")
    .eq("language", "Spanish")
    .eq("level", level)
    .eq("topic", currentTopic)
    .gt("lesson_number", pos.current_lesson ?? 0)
    .order("lesson_number", { ascending: true })
    .limit(1)
    .maybeSingle();

  if (nextInTopic) {
    await patchMemory(userId, {
      curriculum_position: {
        ...pos,
        current_lesson: nextInTopic.lesson_number,
      },
    });
    return;
  }

  // Step 2+: walk forward through the topic sequence and pick the
  // first topic that has at least one lesson (some topics in the
  // spec might not yet have generated lessons — skip those).
  for (let i = currentIdx + 1; i < topicSequence.length; i++) {
    const nextTopic = topicSequence[i];
    const { data: firstLesson } = await sb
      .from("lessons")
      .select("topic, lesson_number")
      .eq("language", "Spanish")
      .eq("level", level)
      .eq("topic", nextTopic)
      .order("lesson_number", { ascending: true })
      .limit(1)
      .maybeSingle();
    if (firstLesson) {
      await patchMemory(userId, {
        curriculum_position: {
          current_topic: firstLesson.topic,
          current_lesson: firstLesson.lesson_number,
          completed_topics: [
            ...(pos.completed_topics ?? []),
            currentTopic,
          ].filter(Boolean),
        },
      });
      return;
    }
  }

  // Fallback for topics not yet in any module — find any lesson in
  // a topic the student hasn't already worked on. Catches lessons
  // that pre-date the modules system or have a typo in the topic key.
  const { data: orphan } = await sb
    .from("lessons")
    .select("topic, lesson_number")
    .eq("language", "Spanish")
    .eq("level", level)
    .neq("topic", currentTopic)
    .order("topic", { ascending: true })
    .order("lesson_number", { ascending: true })
    .limit(1)
    .maybeSingle();

  await patchMemory(userId, {
    curriculum_position: {
      current_topic: orphan?.topic ?? currentTopic,
      current_lesson: orphan?.lesson_number ?? pos.current_lesson,
      completed_topics: [
        ...(pos.completed_topics ?? []),
        currentTopic,
      ].filter(Boolean),
    },
  });
}

// ── Internals ──────────────────────────────────────────────────────────────

async function fetchLesson(args: {
  language: string;
  level: string;
  topic: string;
  lessonNumber: number;
}): Promise<Lesson | null> {
  const sb = getAdminClient();
  const { data } = await sb
    .from("lessons")
    .select("*")
    .eq("language", args.language)
    .eq("level", args.level)
    .eq("topic", args.topic)
    .eq("lesson_number", args.lessonNumber)
    .maybeSingle();
  return (data as Lesson | null) ?? null;
}

async function formatLesson(
  lesson: Lesson,
  teacherId: string | null,
): Promise<string> {
  const systemPrompt = await getTeacherSystemPrompt(teacherId);

  const itemsSummary = lesson.content.items
    .map((i: LessonItem) => {
      if (i.type === "conjugation" && i.conjugation) {
        const lines = Object.entries(i.conjugation)
          .map(([k, v]) => `${k}: ${v}`)
          .join("\n");
        return `${i.target_language} (${i.native_language})\n${lines}`;
      }
      return `${i.target_language} — ${i.native_language}${i.pronunciation_guide ? ` (${i.pronunciation_guide})` : ""}`;
    })
    .join("\n");

  const filledSystem = systemPrompt
    .replace("[MEMORY_JSON]", "{}")
    .replace("[STATE]", "active_structured_lesson")
    .replace("[LAST_20_MESSAGES]", "(none)");

  const result = await chatCompletion(
    [
      { role: "system", content: filledSystem },
      {
        role: "user",
        content: `Format this lesson as a WhatsApp message in your voice. List EVERY vocabulary and phrase item — don't summarise, don't drop any. Group related items together with line breaks (e.g. all days on one block, all months on another). Include the pronunciation guide in parentheses when one is provided. Skip "rule" items unless they're essential context. Keep your own commentary minimal (one short intro line + one short closing line) — the items themselves are the lesson. Do NOT end with any "Want to hear me say..." offer; the audio plays automatically. Cap the whole message at 1100 characters.

LESSON: ${lesson.title}
${lesson.content.introduction}

ITEMS:
${itemsSummary}

SUMMARY: ${lesson.content.summary}`,
      },
    ],
    {
      model: process.env.CHIA_PERSONALITY_MODEL ?? "gpt-4o",
      temperature: 0.85,
      max_tokens: 500,
    },
  );
  return result.trim();
}

async function getTeacherSystemPrompt(
  teacherId: string | null,
): Promise<string> {
  if (!teacherId) return "You are Chia, a Spanish teacher from Valencia.";
  const sb = getAdminClient();
  const { data } = await sb
    .from("teachers")
    .select("system_prompt")
    .eq("id", teacherId)
    .single();
  return (
    (data?.system_prompt as string) ??
    "You are Chia, a Spanish teacher from Valencia."
  );
}

// Re-export for possible future use; not currently consumed externally
export type { LessonContent };
